language: java
jdk: oraclejdk9
services:
  - mysql

sudo: required
dist: trusty

jobs:
  include:
    - stage: Backend
      before_install:
         - cd rest
         - mysql -e 'CREATE DATABASE rental_schema;'
      script: 
         - mvn clean package install
    - stage: Frontend
      node_js: node
      before_install:
        - cd client/rental-service
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sudo apt-get update
        - sudo apt-get install -y libappindicator1 fonts-liberation
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - sudo dpkg -i google-chrome*.deb
      before_script:
        - npm install
        - npm install -g --silent @angular/cli
      script:
        - ng test --watch false --single-run --browsers PhantomJS
stages:
  - Frontend
  - Backend
  
notifications:
email: # only receive email when the build status changes (someone broke the build!)
  on_failure: change
  on_success: change