language: java
jdk: oraclejdk9
services:
  - mysql

jobs:
  include:
    - stage: Backend
      before_install:
         - cd rest
         - mysql -e 'CREATE DATABASE rental_schema;'
      script: 
         - mvn clean package install
    - stage: Frontend
      node_js: node
      before_install:
         - cd client/rental-service
      script:
         - npm install
         - npm install -g --silent @angular/cli
         - ng build --prod
stages:
  - Frontend
  - Backend
