language: java
jdk: oraclejdk9
services:
  - mysql

jobs:
  include:
    - stage: Backend
      before_install:
         - cd rest
         - mysql -e 'CREATE DATABASE rental_schema;'
      script: 
         - mvn clean package install
    - stage: Frontend
      node_js: node
      before_install:
         - cd client/rental-service
      before_script:
         - npm install
         - npm install -g --silent @angular/cli
      script:
         - npm test --single-run --browsers PhantomJS
stages:
  - Frontend
  - Backend
  
notifications:
email: # only receive email when the build status changes (someone broke the build!)
  on_failure: change
  on_success: change