language: java
jdk: oraclejdk8
node_js: node

jobs:
  include:
    - stage: Backend
      before_install:
         - cd rest
      script: 
         - mvn clean package install
    - stage: Frontend
      before_install:
         - cd client/rental-service
      script:
         - npm install -g --silent @angular/cli
         - ng build --prod
stages:
  - Backend
  - Frontend
