jobs:
  include:
    - stage: Frontend
      before_install:
         - cd client/rental-service
      before_script:
         - npm install -g --silent @angular/cli
      script:
         - ng build --prod
    - stage: Backend
      before_install:
         - cd rest
      script: 
         - jdk_switcher use oraclejdk9
         - mvn clean package install
